
SELECT /*L10*/  DISTINCT 
          [icmpcs] AS [icmpcs]
         ,[parameter] AS [parameter]
         ,Max([value]) AS [value]
         ,[STARTTS] AS [STARTTS]
         ,[UTC] AS [UTC]
         ,[TZONE] AS [TZONE]
         ,[TZS] AS [TZS]
         ,[SFOLDER] AS [SFOLDER]
         ,[FAC] AS [FAC]
         ,[MARS] AS [MARS]
         ,[MARSN] AS [MARSN]
         ,[RIMS] AS [RIMS]
         ,[EIMS] AS [EIMS]
         ,[ARIES] AS [ARIES]
         ,[OASYS] AS [OASYS]
         ,[MONGO] AS [MONGO]
         ,[MMS] AS [MMS]
         ,[MMSI] AS [MMSI]
         ,[TOOLLOG] AS [TOOLLOG]
         ,[VFMARS] AS [VFMARS]
         ,[VFARIES] AS [VFARIES]
         ,[VFMONGO] AS [VFMONGO]
         ,[CSRPATH] AS [CSRPATH]
         ,[MMSPATH] AS [MMSPATH]
         ,[MIPPATH] AS [MIPPATH]
         ,[LURL] AS [LURL]
         ,[IREPOP] AS [IREPOP]
         ,[UNDERDEV] AS [UNDERDEV]
         ,[CSRV] AS [CSRV]
         ,[MMSV] AS [MMSV]
FROM
(
SELECT /*L0*/  
          a0.[icmpcs] AS [icmpcs]
         ,a0.[parameter] AS [parameter]
         ,a0.[value] AS [value]
         ,'<<<STARTTS>>>' AS [STARTTS]
         ,'<<<UTC>>>' AS [UTC]
         ,'<<<TZONE>>>' AS [TZONE]
         ,'<<<TZS>>>' AS [TZS]
         ,'<<<SFOLDER>>>' AS [SFOLDER]
         ,'<<<FAC>>>' AS [FAC]
         ,'<<<MARS>>>' AS [MARS]
         ,'<<<MARSN>>>' AS [MARSN]
         ,'<<<RIMS>>>' AS [RIMS]
         ,'<<<EIMS>>>' AS [EIMS]
         ,'<<<ARIES>>>' AS [ARIES]
         ,'<<<OASYS>>>' AS [OASYS]
         ,'<<<MONGO>>>' AS [MONGO]
         ,'<<<MMS>>>' AS [MMS]
         ,'<<<MMSI>>>' AS [MMSI]
         ,'<<<TOOLLOG>>>' AS [TOOLLOG]
         ,'<<<VFMARS>>>' AS [VFMARS]
         ,'<<<VFARIES>>>' AS [VFARIES]
         ,'<<<VFMONGO>>>' AS [VFMONGO]
         ,'<<<CSRPATH>>>' AS [CSRPATH]
         ,'<<<MMSPATH>>>' AS [MMSPATH]
         ,'<<<MIPPATH>>>' AS [MIPPATH]
         ,'<<<LURL>>>' AS [LURL]
         ,'<<<IREPOP>>>' AS [IREPOP]
         ,'<<<UNDERDEV>>>' AS [UNDERDEV]
         ,'<<<CSRV>>>' AS [CSRV]
         ,'<<<MMSV>>>' AS [MMSV]
FROM 
[ICMPCS_config] a0
WHERE
              a0.[icmpcs] = 'ICMPCS' 
) t /*L0*/
GROUP BY 
          [icmpcs]
         ,[parameter]
         ,[STARTTS]
         ,[UTC]
         ,[TZONE]
         ,[TZS]
         ,[SFOLDER]
         ,[FAC]
         ,[MARS]
         ,[MARSN]
         ,[RIMS]
         ,[EIMS]
         ,[ARIES]
         ,[OASYS]
         ,[MONGO]
         ,[MMS]
         ,[MMSI]
         ,[TOOLLOG]
         ,[VFMARS]
         ,[VFARIES]
         ,[VFMONGO]
         ,[CSRPATH]
         ,[MMSPATH]
         ,[MIPPATH]
         ,[LURL]
         ,[IREPOP]
         ,[UNDERDEV]
         ,[CSRV]
         ,[MMSV]

