# ***************************************************************************
# Module:            heatMap
# Creation date:     May 2, 2024
# Written by:        Farzin Guilak
# Modification:      $Id: lemsHeatMap.py,v 1.27 2024/05/17 00:05:10 fguilak Exp $
# **************************************************************************

import logging
from matplotlib import pyplot as plt
from matplotlib import gridspec
from matplotlib.colors import to_rgb
import numpy as np
import pylems as lems
import pandas as pd
import re

from pylems_utils import probability_count

# from lemsUtilities import utils

__version__ = '$Id: lemsHeatMap.py,v 1.27 2024/05/17 00:05:10 fguilak Exp $'

# =========================================================================

class hmData:
    def __init__( self, rawDF, boundsDF ):
        self._rawDF = rawDF
        self._boundsDF = boundsDF
        self._aqn = re.compile( '.*-J[0-9]+$' )

    def _getBounds( self ):
        # Extract cluster boundaries for specified variable into a list
        bounds = [float(x) for x in self._boundsDF[ self._boundsDF[ 'C0' ]==self._rawVar]['bounds'].iloc[-1].tolist()]

        # This adjusts the boundary when the min and lowest bound are the same. In the
        # case of two clusters, without this correction the heat map effectively shows
        # only one row/column for the affected variable.
        if self._min == bounds[0]:
            sortVar = sorted( self._data )
            nextVal = [ x for x in sortVar if x > bounds[0]]
            bounds[0] = (bounds[0] + nextVal[0]) / 2
            logging.warning( f'{self._var} lowest bound==min value={self._min}, adjusting to {bounds[0]}' )

        return [self._min] + bounds + [self._max] 

    def _setVar( self, aqVarName ):
        self._var = aqVarName

        # Make sure variable is an autoQuant numeric
        if not self._aqn.match( aqVarName ):
            raise ValueError( f'plotHeatMap|bad variable <{aqVarName}> - must provide autoQuant numeric' )

        # Strip -Jn from autoQuant column name
        self._rawVar = re.sub( '-J[0-9]+$', '', aqVarName )
        
        # Extract unquantized variables for histograms
        try:
            self._data = self._rawDF[ self._rawVar ]
        except KeyError as err:
            logging.error( f'plotHeatMap|bad variable name: {err}' )
            return None

        self._min = self._data.min()
        self._max = self._data.max()

        self._lines = self._getBounds()

        # Range to get matrix dims from number of lines. _lines includes boundaries at
        # edges so subtract one to get the number of bins
        self._range = range( len( self._lines ) - 1 )

# =========================================================================

# --------------------
# Function to return a good contrasting color for text on the supplied background
# color.  Override defaults with the light and dark parameters
#
def textColor( bgColor, light='white', dark='black' ):
    r, g, b = to_rgb( bgColor )
    lum = 0.299 * r + 0.587 * g + 0.114 * b
    return light if lum < 0.5 else dark

class lemsHeatMap:
    """Class to generate heatmap depiction of posterior/likelihood table.

    Given a LEMS store, raw (unquantized) data file, and `autoQuant` qInfo file, generate
    a figure including a heatmap depiction of the posterior/likelihood table generated by
    LEMS for two independent variables against an outcome variable.

    The heatmap shows colors corresponding to the posterior probability or likelihood of
    the two independent variables against the specified value of the outcome.  Colors are
    by region defined by `autoQuant` bins.  The regions of the heatmap are annotated with
    the episode counts corresponding to the regions.

    The axes of the heatmap show histograms of the unquantized independent variables
    along with `autoQuant` boundaries and bin labels.

        """

    def __init__( self, baseName, lemsStore=None, rawData=None, qInfo=None ):
        """Constructor for `lemsHeatMap` class.
        
        The constructor takes several parameters that are assumed to be invariant for all
        heatmap plots generated by the class.

        Parameters
        ----------
        baseName : string
            Project name that's used to title plots.  Use a short string or "" for none

        lemsStore : LEMS Connection object to a previously-ingested dataset

        rawData : string
            File name of original (unquantized) CSV-format data file

        qInfo : string
            File name of `autoQuant` CSV-format `qInfo` file.  Used to obtain quantization 
            bounds to generate bin boundaries and labels
        """

        self._reset()

        self._baseName = baseName

        if lemsStore is None:
            self._lemsStore = 'LEMS-' + baseName
        else:
            self._lemsStore = lemsStore

        if rawData is None:
            self._dataFile = baseName + '.csv'
        else:
            self._dataFile = rawData

        if qInfo is None:
            self._qInfo = 'qInfo-' + baseName + '.csv'
        else:
            self._qInfo = qInfo

        self._initFiles()


    def _reset( self ):
        self._dataFile = None
        self._ldb = None
        self._outcomeVar = None
        self._outcomeVal = None
        self._qInfo = None

        self.binAnnots = True         # display bin names on histograms
        self.xHistBins = 50           # number of bins used for X histogram
        self.yHistBins = 50           # number of bins used for Y histogram
        self.xHistColor = '#2d5b80'   # X histogram color
        self.yHistColor = '#2d5b80'   # Y histogram color
        self.cntAnnots = True         # display counts on heat map
        self.zeroCntAnnots = False    # display 0 counts on heat map
        self.cMap = 'viridis'         # colormap used to display heat map
        self.figSize = (10,8)         # initial figure size



    def _initFiles( self ):
        try:
            self._ldb = lems.Connection( self._lemsStore )
        except:
            logging.error( f'lemsHeatMap|exception in lems.Connection({self._lemsStore})' )
            raise

        try:
            rawDF = pd.read_csv( self._dataFile, low_memory=False )
        except:
            logging.error( f'lemsHeatMap|exception opening raw datafile: {self._dataFile}' )
            raise

        # Need column names for a variable number of columns to handle missing columns due
        # to varying number of cluster boundaries. Start by finding the maximum number of
        # columns in the qInfo file
        maxCol = 0
        try:
            with open( self._qInfo, 'r' ) as f:
                for line in f:
                    maxCol = max( maxCol, len( line.split( ',' )))
        except:
            logging.error( f'lemsHeatMap|exception opening qInfo file: {self._qInfo}' )
            raise

        # Rename the columns to handle the maximum number.  C0 will always be column name
        qColNames = [ 'C' + str(i) for i in range ( maxCol ) ]
        qDF = pd.read_csv( self._qInfo, header=None, names=qColNames  ) 

        # Pull out the bounds columns.  qInfo format fixes the first 3 (name, nClusts, gvf)
        boundsCols = qDF.columns[3:]

        # Get the numeric data and drop NAs (vars with fewer bounds than the max)
        boundsSeries = qDF[boundsCols].apply( lambda row: row.dropna().values, axis=1 )

        # Finally, construct a new dataframe with column names and boundaries
        boundsDF = pd.DataFrame( {'bounds':boundsSeries} )
        boundsDF.insert( 0, "C0", qDF['C0'])

        # Instant the heat map raw data classes for X and Y variables.  Variables names
        # set by plotHeatMap method for each plot
        self._xs = hmData( rawDF, boundsDF )
        self._ys = hmData( rawDF, boundsDF )


    def _computeProb( self, varX, xBin, varY, yBin, pType ):
        # Convert bin numbers to cluster names
        x = f'J{xBin+1}'
        y = f'J{yBin+1}'

        # Try blocks to handle exception for zero denominator count from lems
        # TBD: update when probability_count moved to lemsUtilities
        try:
            if pType == "Posterior":
                pVal  = probability_count( self._ldb,
                                           { varX:x, varY:y },
                                           { self._outcomeVar:self._outcomeVal })
            else:
                pVal = probability_count( self._ldb,
                                          { self._outcomeVar:self._outcomeVal },
                                          { varX:x, varY:y })
            
        except ValueError:
            pVal = (0.0, 0)
        except KeyError:
            raise lems.LemsException( f'computeProb|outcome variable <{self._outcomeVar}> does not exist')
        except lems.LemsException:
            raise lems.LemsException( f'computeProb|bad value <{self._outcomeVal}> specified for outcome <{self._outcomeVar}>')

        return pVal
        
    def _annotBins( self, ax, lines, dim='x' ):
        if not self.binAnnots:
            return
        
        if dim == 'x':
            _,yMax = ax.get_ylim()
            yLoc = 0.85 * yMax
        else:
            yMax,_ = ax.get_xlim()
            yLoc = 0.95 * yMax

        for lIdx in range( len( lines )-1 ):
            xLoc = (( lines[lIdx] + lines[lIdx+1])/2  )
            lab = f'J{str(lIdx+1)}'

            if dim == 'x':
                ax.text( xLoc, yLoc, lab )
            else:
                ax.text( yLoc, xLoc, lab, rotation=90 )

    def _annotCnts( self, ax, pcMat ):
        if not self.cntAnnots:
            return
        
        cm = plt.get_cmap( self.cMap )
        maxProb = max(first for row in pcMat for first,_ in row)

        for i in self._xs._range:
            midX = (self._xs._lines[i] + self._xs._lines[i + 1]) / 2
            for j in self._ys._range:
                prob,cnt = pcMat[j][i]
                tileColor = cm( prob / maxProb )
                cntColor = textColor( tileColor )
                midY = (self._ys._lines[j] + self._ys._lines[j + 1]) / 2

                if prob == 0 and not self.zeroCntAnnots:
                    continue
                
                ax.text( midX, midY, cnt, color=cntColor, ha='center', va='center', fontsize=9 )


    def _makePlot( self ):
        # Set up ranges and generate a mesh for the probability heatmap
        x = np.linspace( self._xs._min, self._xs._max, 500 )
        y = np.linspace( self._ys._min, self._ys._max, 500 )
        X, Y = np.meshgrid( x, y )
        Z = np.zeros_like( X )
        
        # Allocate a matrix for bin probabilities and counts
        pcMat = [[ (0,0) for x in self._xs._range ] for y in self._ys._range]

        # Calculate the probability for each region and assign it to Z
        for i in self._xs._range:
            for j in self._ys._range:
                # Get the bin edges
                x_left, x_right = self._xs._lines[i], self._xs._lines[i + 1]
                y_bottom, y_top = self._ys._lines[j], self._ys._lines[j + 1]

                # Compute the probability for this bin
                try:
                    bin_prob,bin_cnt = self._computeProb( self._xs._var, i, self._ys._var, j, self._probType )
                except (KeyError, lems.LemsException):
                    raise

                # Assign the probability to corresponding region in Z
                Z[(X >= x_left) & (X <= x_right) & (Y >= y_bottom) & (Y <= y_top)] = bin_prob

                # And the corresponding count to the matrix
                pcMat[ j ][ i ] = (bin_prob,bin_cnt)

        # Set up the figure and grid 
        fig = plt.figure( figsize=self.figSize )
        gs = gridspec.GridSpec( 2, 3,
                                width_ratios=[1, 5, 0.2],
                                height_ratios=[1,5],
                                hspace=0.05,
                                wspace=0.35 )

        # Heatmap plot
        ax_heatmap = plt.subplot(gs[1, 1])
        im = ax_heatmap.imshow( Z,
                                extent=(x.min(), x.max(), y.min(), y.max()),
                                origin='lower',
                                cmap=self.cMap,
                                aspect='auto')

        self._annotCnts( ax_heatmap, pcMat )

        # Histogram for x variable
        ax_histx = plt.subplot(gs[0, 1], sharex=ax_heatmap)
        ax_histx.hist( self._xs._data,
                       bins=self.xHistBins,
                       orientation='vertical',
                       color=self.xHistColor,
                       alpha=0.8 )
        ax_histx.xaxis.set_label_position('top')
        ax_histx.set_xlabel( self._xs._rawVar )
        self._annotBins( ax_histx, self._xs._lines )

        # Histogram for y variable
        ax_histy = plt.subplot(gs[1, 0], sharey=ax_heatmap)
        ax_histy.hist( self._ys._data,
                       bins=self.yHistBins,
                       orientation='horizontal',
                       color=self.yHistColor,
                       alpha=0.8 )
        ax_histy.invert_xaxis()  # Invert so base is next to the heatmap
        ax_histy.set_ylabel( self._ys._rawVar )
        self._annotBins( ax_histy, self._ys._lines, 'y' )

        # Adjust layout and remove axis labels for histograms
        plt.setp( ax_histx.get_xticklabels(), visible=False )
        plt.setp( ax_histy.get_yticklabels(), visible=False )
        ax_histx.get_yaxis().set_visible( False )
        ax_histy.get_xaxis().set_visible( False )

        # Create an axis for the colorbar
        ax_colorbar = plt.subplot( gs[1, 2] )
        plt.colorbar( im, cax=ax_colorbar )

        # Add vertical lines at the inner bin edges
        for xline in self._xs._lines[1:-1]:
            ax_heatmap.axvline( x=xline, color='white', linestyle='--' )
            ax_histx.axvline( x=xline, color='#444444', linestyle='--' )

        # Add horizontal lines at the bin edges
        for yline in self._ys._lines[1:-1]:
            ax_heatmap.axhline(y=yline, color='white', linestyle='--')
            ax_histy.axhline(y=yline, color='#444444', linestyle='--')

        # Move y-axis of heatmap to the left
        ax_heatmap.yaxis.tick_left()
        ax_heatmap.yaxis.set_label_position("left")

        titleStr = f'{self._baseName} {self._probType}s for "{self._outcomeVar}"="{self._outcomeVal}"'
        ax_histx.set_title( titleStr, pad=30 )

        return fig
        

    def setOutcome( self, var, val ):
        """ Accessor to set outcome variable and value.

        These values must be set prior to running `plotHeatMap`

        Parameters
        ----------
        var : string
            Variable name to be used as outcome in posterior/likelihood calculations

        val : string
            `autoQuant` bin value to be used to filter rows of probability table

        """
        
        self._outcomeVar = var
        self._outcomeVal = val
        

    def plotHeatmap( self, varX, varY, pType='Likelihood' ):
        """Method to generate a heatmap figure
        
        This method generates a heatmap figure using colors to represent either the
        likelihood or posterior probability of two independent variables associated with
        an outcome variable and value specified using the `setOutcome` method.

        Parameters
        ----------
        varX : string
            Variable name to use on the X axis of the histogram

        varY : string
            Variable name to use on the Y axis of the histogram

        rawData : string
            File name of original (unquantized) CSV-format data file

        pType : string - optional
            Must be either 'Likelihood' (default), or 'Posterior'

        Returns
        -------
        `matplotlib` `Figure` object that can be shown or saved


        Additional Options
        ------------------
        The following instance variables can be set directly to change subsequent heatmaps.
        Assuming you have an instance `hm` created already (values shown are defaults):

            hm.binAnnots = True         # display bin names on histograms
            hm.xHistBins = 50           # number of bins used for X histogram
            hm.yHistBins = 50           # number of bins used for Y histogram
            hm.xHistColor = '#2d5b80'   # X histogram color
            hm.yHistColor = '#2d5b80'   # Y histogram color
            hm.cntAnnots = True         # display counts on heat map
            hm.zeroCntAnnots = False    # display 0 counts on heat map
            hm.cMap = 'viridis'         # colormap used to display heat map
            hm.figSize = (10,8)         # initial figure size

        """

        if self._outcomeVal is None or self._outcomeVar is None:
            logging.error( "plotHeatMap|set outcome variable and value using `setOutcome` method prior to plotting" )
            return

        if pType != 'Likelihood' and pType != 'Posterior':
            logging.error( 'plotHeatMap|pType must be "Likelihood" (default), or "Posterior"')
            raise ValueError( f'plotHeatMap|bad probability type <{pType}>' )
            
        self._probType = pType

        try:
            # Set X and Y variables for the heatmap and generate the plot
            self._xs._setVar( varX )
            self._ys._setVar( varY )
            heatMapFig = self._makePlot()
        except (KeyError, lems.LemsException) as err:
            raise err

        return heatMapFig
